/**
 * `council export <panel> --format share` renderer.
 *
 * Produces a polished, launch-ready markdown document that is safe to
 * paste into a PR, an RFC, or a Slack thread. Unlike the default
 * `markdown` format (a faithful transcript dump), `share` leads with the
 * decision-useful summary — the panel roster and each panellist's most
 * recent recorded position — before tucking the full transcript at the
 * end.
 *
 * Pure projection of the persisted session: no engine, no LLM, no
 * network. Every section is derived only from data Council actually
 * stores for the panel (panel, experts, debate, turns).
 *
 * Honesty constraint: Council persists only expert/human turns (see
 * `src/memory/persister.ts`) — it never persists a synthesized
 * conclusion. `council conclude` does run an LLM synthesis, but it prints
 * the result to stdout and persists nothing. So the `share` export cannot
 * contain a synthesized recommendation, key-disagreement breakdown, or
 * next-action list, and it must not pretend otherwise. Instead of
 * fabricating those sections (or implying that re-exporting after
 * `conclude` would fill them in), this renderer surfaces the real data it
 * has — each expert's latest turn, under "Panel Positions" — and states
 * plainly in the "Recommendation" section that no synthesis is stored,
 * pointing the reader at `council conclude` whose stdout they can copy in.
 */
import type { Turn } from "../../memory/repositories/turns.js";
import type { TranscriptDocument } from "../../memory/transcript.js";

import { sanitizeExportBlockLines, sanitizeExportLine } from "./export-sanitize.js";

const PLACEHOLDER_PROMPT = "_Not recorded._";
const PLACEHOLDER_ROSTER = "_No panellists recorded._";
const PLACEHOLDER_POSITIONS = "_No expert positions recorded._";
const PLACEHOLDER_TRANSCRIPT = "_No turns recorded._";

/**
 * Render a {@link TranscriptDocument} as a shareable markdown document.
 *
 * Sections are emitted in a fixed order: Title → Prompt → Panel roster →
 * Panel Positions → Recommendation → Transcript.
 */
export function renderShare(doc: TranscriptDocument): string {
  const lines: string[] = [];

  // 1. Title — a human-readable headline plus a deterministic metadata line.
  lines.push(
    `# ${sanitizeExportLine(firstNonEmpty(doc.panel.topic, doc.originalPrompt, doc.panel.name))}`,
  );
  lines.push("");
  lines.push(renderSubtitle(doc));
  lines.push("");

  // 2. Prompt / Topic.
  pushSection(lines, "Prompt", () => {
    const prompt = sanitizeExportLine(doc.originalPrompt.trim());
    return [prompt.length > 0 ? prompt : PLACEHOLDER_PROMPT];
  });

  // 3. Panel roster — each expert and the model behind them.
  pushSection(lines, "Panel", () => {
    if (doc.experts.length === 0) return [PLACEHOLDER_ROSTER];
    return doc.experts.map(
      (e) =>
        `- **${sanitizeExportLine(e.displayName)}** (\`${sanitizeExportLine(
          e.slug,
        )}\`) — ${sanitizeExportLine(e.model)}`,
    );
  });

  // 4. Panel positions — each expert's most recent recorded turn. This is
  //    real persisted data (not a synthesized comparison), labelled as such.
  pushSection(lines, "Panel Positions", () => renderPositions(doc));

  // 5. Recommendation — Council never persists a synthesized recommendation
  //    (`conclude` prints to stdout without saving), so say so plainly rather
  //    than fabricating one or implying that re-exporting would fill it in.
  pushSection(lines, "Recommendation", () => [renderRecommendationNote(doc)]);

  // 6. Full transcript.
  pushSection(lines, "Transcript", () => renderTranscriptBody(doc));

  lines.push("---");
  lines.push(
    `_Generated by Council — \`council export ${sanitizeExportLine(
      doc.panel.name,
    )} --format share\`_`,
  );
  return lines.join("\n") + "\n";
}

function renderSubtitle(doc: TranscriptDocument): string {
  const parts = [
    `Panel: ${sanitizeExportLine(doc.panel.name)}`,
    `Status: ${sanitizeExportLine(doc.latestDebate.status)}`,
  ];
  if (doc.latestDebate.endedAt) {
    parts.push(`Concluded: ${sanitizeExportLine(doc.latestDebate.endedAt)}`);
  }
  return `_${parts.join(" · ")}_`;
}

function renderRecommendationNote(doc: TranscriptDocument): string {
  return (
    `_Council records the panel's deliberation but does not persist a synthesized ` +
    `recommendation, so the \`share\` export cannot include one. Run ` +
    `\`council conclude ${sanitizeExportLine(doc.panel.name)}\` to generate a recommendation — it prints to ` +
    `stdout for you to copy in here._`
  );
}

function pushSection(lines: string[], heading: string, body: () => readonly string[]): void {
  lines.push(`## ${heading}`);
  lines.push("");
  for (const line of body()) lines.push(line);
  lines.push("");
}

/**
 * Render each expert's most recent recorded turn as their "position".
 * Iterates experts in roster order for determinism; experts with no
 * recorded turn are skipped. Returns an honest placeholder when no expert
 * turn exists at all.
 */
function renderPositions(doc: TranscriptDocument): readonly string[] {
  const lastTurnByExpertId = new Map<string, Turn>();
  for (const t of doc.turns) {
    if (t.expertId) lastTurnByExpertId.set(t.expertId, t);
  }

  const out: string[] = [];
  for (const e of doc.experts) {
    const turn = lastTurnByExpertId.get(e.id);
    if (!turn) continue;
    out.push(`### ${sanitizeExportLine(e.displayName)}`);
    out.push("");
    for (const para of sanitizeExportBlockLines(turn.content)) out.push(`> ${para}`);
    out.push("");
  }
  if (out.length === 0) return [PLACEHOLDER_POSITIONS];
  // Drop the trailing blank — `pushSection` adds its own separator.
  if (out[out.length - 1] === "") out.pop();
  return out;
}

function renderTranscriptBody(doc: TranscriptDocument): readonly string[] {
  const displayNameByExpertId = new Map<string, string>();
  for (const e of doc.experts) displayNameByExpertId.set(e.id, sanitizeExportLine(e.displayName));

  if (doc.turns.length === 0) return [PLACEHOLDER_TRANSCRIPT];

  const out: string[] = [];
  let lastRound = -1;
  for (const t of doc.turns) {
    if (t.round !== lastRound) {
      out.push(`### Round ${t.round + 1}`);
      out.push("");
      lastRound = t.round;
    }
    const speaker = t.expertId
      ? (displayNameByExpertId.get(t.expertId) ?? sanitizeExportLine(t.speakerKind))
      : sanitizeExportLine(t.speakerKind);
    out.push(`**${speaker}**`);
    out.push("");
    for (const para of sanitizeExportBlockLines(t.content)) out.push(`> ${para}`);
    out.push("");
  }
  // Drop the trailing blank — `pushSection` adds its own separator.
  if (out[out.length - 1] === "") out.pop();
  return out;
}

function firstNonEmpty(...values: readonly (string | null | undefined)[]): string {
  for (const value of values) {
    if (value && value.trim().length > 0) return value.trim();
  }
  return "Untitled panel";
}
