/**
 * `council export <panel> --format share` renderer.
 *
 * Produces a polished, launch-ready markdown document that is safe to
 * paste into a PR, an RFC, or a Slack thread. Unlike the default
 * `markdown` format (a faithful transcript dump), `share` leads with the
 * decision-useful summary — panel roster, key tensions, the
 * recommendation, and concrete next actions — and tucks the full
 * transcript at the end.
 *
 * Pure projection of the persisted session: no engine, no LLM, no
 * network. Every section is derived only from data already stored for
 * the panel (panel, experts, debate, turns). When the data backing a
 * synthesis-derived section was never recorded (because `council
 * conclude` has not run and persisted a synthesis), the section prints an
 * explicit, honest "Not recorded" placeholder rather than fabricating a
 * conclusion, recommendation, or dissent.
 *
 * Synthesis source: a persisted moderator turn (`speakerKind ===
 * "moderator"`) is treated as the recorded synthesis — see
 * `src/memory/repositories/turns.ts` ("a moderator synthesis"). Its
 * content may be structured JSON (the shape `council conclude` emits:
 * `{ tensions, recommendation, nextActions }`) or free-form text. JSON is
 * parsed into the dedicated sections; plain text is surfaced verbatim as
 * the recommendation. Moderator turns are intentionally omitted from the
 * rendered transcript so the synthesis appears only once, in its labelled
 * sections.
 */
import { z } from "zod";

import type { Turn, SpeakerKind } from "../../memory/repositories/turns.js";
import type { TranscriptDocument } from "../../memory/transcript.js";

/** Turns with this speaker kind are treated as the recorded synthesis. */
const SYNTHESIS_SPEAKER: SpeakerKind = "moderator";

const PLACEHOLDER_PROMPT = "_Not recorded._";
const PLACEHOLDER_ROSTER = "_No panellists recorded._";
const PLACEHOLDER_TENSIONS =
  "_Not recorded — no tensions were captured. Run `council conclude` to synthesize the panel's disagreements._";
const PLACEHOLDER_RECOMMENDATION = "_Not recorded — run `council conclude` first._";
const PLACEHOLDER_NEXT_ACTIONS =
  "_Not recorded — run `council conclude` to derive recommended next actions._";
const PLACEHOLDER_TRANSCRIPT = "_No turns recorded._";

/** Structured fields a recorded synthesis may contribute to the document. */
interface ParsedSynthesis {
  readonly tensions?: readonly string[];
  readonly recommendation?: string;
  readonly nextActions?: readonly string[];
}

const SynthesisSchema = z.object({
  tensions: z.array(z.string()).optional(),
  recommendation: z.string().optional(),
  nextActions: z.array(z.string()).optional(),
});

/**
 * Render a {@link TranscriptDocument} as a shareable markdown document.
 *
 * Sections are emitted in a fixed order: Title → Prompt → Panel roster →
 * Key Disagreements → Recommendation → Next Actions → Transcript.
 */
export function renderShare(doc: TranscriptDocument): string {
  const synthesis = parseSynthesis(doc.turns);
  const lines: string[] = [];

  // 1. Title — a human-readable headline plus a deterministic metadata line.
  lines.push(`# ${firstNonEmpty(doc.panel.topic, doc.originalPrompt, doc.panel.name)}`);
  lines.push("");
  lines.push(renderSubtitle(doc));
  lines.push("");

  // 2. Prompt / Topic.
  pushSection(lines, "Prompt", () => {
    const prompt = doc.originalPrompt.trim();
    return [prompt.length > 0 ? prompt : PLACEHOLDER_PROMPT];
  });

  // 3. Panel roster — each expert and the model behind them.
  pushSection(lines, "Panel", () => {
    if (doc.experts.length === 0) return [PLACEHOLDER_ROSTER];
    return doc.experts.map((e) => `- **${e.displayName}** (\`${e.slug}\`) — ${e.model}`);
  });

  // 4. Key disagreements / tensions.
  pushSection(lines, "Key Disagreements & Tensions", () => {
    const tensions = synthesis?.tensions ?? [];
    if (tensions.length === 0) return [PLACEHOLDER_TENSIONS];
    return tensions.map((t) => `- ${t}`);
  });

  // 5. Recommendation / Decision.
  pushSection(lines, "Recommendation", () => {
    const recommendation = synthesis?.recommendation?.trim() ?? "";
    if (recommendation.length === 0) return [PLACEHOLDER_RECOMMENDATION];
    return recommendation.split("\n");
  });

  // 6. Next actions.
  pushSection(lines, "Next Actions", () => {
    const actions = synthesis?.nextActions ?? [];
    if (actions.length === 0) return [PLACEHOLDER_NEXT_ACTIONS];
    return actions.map((a, i) => `${i + 1}. ${a}`);
  });

  // 7. Full transcript (synthesis turns excluded — surfaced above).
  pushSection(lines, "Transcript", () => renderTranscriptBody(doc));

  lines.push("---");
  lines.push(`_Generated by Council — \`council export ${doc.panel.name} --format share\`_`);
  return lines.join("\n") + "\n";
}

function renderSubtitle(doc: TranscriptDocument): string {
  const parts = [`Panel: ${doc.panel.name}`, `Status: ${doc.latestDebate.status}`];
  if (doc.latestDebate.endedAt) parts.push(`Concluded: ${doc.latestDebate.endedAt}`);
  return `_${parts.join(" · ")}_`;
}

function pushSection(lines: string[], heading: string, body: () => readonly string[]): void {
  lines.push(`## ${heading}`);
  lines.push("");
  for (const line of body()) lines.push(line);
  lines.push("");
}

function renderTranscriptBody(doc: TranscriptDocument): readonly string[] {
  const displayNameByExpertId = new Map<string, string>();
  for (const e of doc.experts) displayNameByExpertId.set(e.id, e.displayName);

  const transcriptTurns = doc.turns.filter((t) => t.speakerKind !== SYNTHESIS_SPEAKER);
  if (transcriptTurns.length === 0) return [PLACEHOLDER_TRANSCRIPT];

  const out: string[] = [];
  let lastRound = -1;
  for (const t of transcriptTurns) {
    if (t.round !== lastRound) {
      out.push(`### Round ${t.round + 1}`);
      out.push("");
      lastRound = t.round;
    }
    const speaker = t.expertId
      ? (displayNameByExpertId.get(t.expertId) ?? t.speakerKind)
      : t.speakerKind;
    out.push(`**${speaker}**`);
    out.push("");
    for (const para of t.content.split("\n")) out.push(`> ${para}`);
    out.push("");
  }
  // Drop the trailing blank — `pushSection` adds its own separator.
  if (out[out.length - 1] === "") out.pop();
  return out;
}

/**
 * Derive the recorded synthesis from a panel's turns, or `null` when none
 * was persisted. The most recent moderator turn wins; its content is
 * parsed as structured JSON when possible, otherwise treated as a
 * free-form recommendation. Never invents fields that were not recorded.
 */
function parseSynthesis(turns: readonly Turn[]): ParsedSynthesis | null {
  const synthesisTurns = turns.filter((t) => t.speakerKind === SYNTHESIS_SPEAKER);
  const last = synthesisTurns[synthesisTurns.length - 1];
  if (!last) return null;
  const content = last.content.trim();
  if (content.length === 0) return null;

  const parsed = tryParseJsonObject(content);
  if (parsed !== null) {
    const result = SynthesisSchema.safeParse(parsed);
    if (result.success) {
      const tensions = (result.data.tensions ?? []).filter((t) => t.trim().length > 0);
      const nextActions = (result.data.nextActions ?? []).filter((a) => a.trim().length > 0);
      const recommendation = result.data.recommendation?.trim() ?? "";
      if (tensions.length > 0 || nextActions.length > 0 || recommendation.length > 0) {
        return {
          ...(tensions.length > 0 ? { tensions } : {}),
          ...(recommendation.length > 0 ? { recommendation } : {}),
          ...(nextActions.length > 0 ? { nextActions } : {}),
        };
      }
    }
  }

  // Free-form synthesis: the whole turn is the recommendation.
  return { recommendation: content };
}

function tryParseJsonObject(text: string): Record<string, unknown> | null {
  try {
    const value: unknown = JSON.parse(text);
    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      return value as Record<string, unknown>;
    }
    return null;
  } catch {
    return null;
  }
}

function firstNonEmpty(...values: readonly (string | null | undefined)[]): string {
  for (const value of values) {
    if (value && value.trim().length > 0) return value.trim();
  }
  return "Untitled panel";
}
